# Generated by Django 4.0.5 on 2022-06-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='groups',
            new_name='group',
        ),
    ]
