# Generated by Django 4.0.5 on 2022-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('animals', '0003_rename_characteriscs_animal_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(related_name='characteristics', to='characteristics.characteristic'),
        ),
    ]
